### ISSUE TITLE
Disabled Mob Spawning

### ISSUE THREAD

**Issue by BlueJay5773** [ickerio/factions#106] opened 2023-08-11 00:30 UTC
### Is your feature request related to a problem?

I personally tend to build very dark builds (slums, etc) so the fact that mobs spawn is a major turn off. 

### Describe the solution you'd like.

Have an option to disable mob spawning inside claims (config, or something)

### Describe alternatives you've considered.

Personally I tried to light up the area, but it didn't look good at all. I also have used other mods but it seems like this is hard to find. Playing on a server that does not do plugins

**Comment by Cookieguy172** [comment] 2023-08-11 00:43
it seemed like it had to restart (the server) for it to take effect.

**Comment by BlueZeeKing** [comment] 2023-12-27 04:09
Duplicate of #42

**Closed by BlueZeeKing** 2023-12-27 04:09 UTC
